name: openttd-server
adopt-info: openttd-server
summary: OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: >
  OpenTTD is an open source simulation game based upon the popular
  Microprose game Transport Tycoon Deluxe, written by Chris Sawyer.
  It attempts to mimic the original game as closely as possible while
  extending it with new features.
  This is an unofficial snap containing both the engine and open* asset packs.

  * Upstream project: https://www.openttd.org/
  * Snapcraft.yaml repository: https://github.com/zoltantamasvajda/openttd-server

grade: stable
confinement: strict
base: core20
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  openttd-server:
    command: usr/games/openttd/scripts/entrypoint.sh
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  openttd-server:
    plugin: cmake
    source: https://github.com/OpenTTD/OpenTTD.git
    override-pull: |
      snapcraftctl pull
      VERSION="$(git tag --list --sort=version:refname | grep -v -E '(-RC|beta)' | tail -n1)"
      git checkout "$VERSION"
      snapcraftctl set-version "$VERSION"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_DATADIR=games
      - -DCMAKE_INSTALL_BINDIR=games/openttd
      - -DCMAKE_BUILD_TYPE=Release
      - -DOPTION_DEDICATED=ON
    build-packages:
      - zlib1g-dev
      - liblzma-dev
      - liblzo2-dev
      - libpng-dev
    stage-packages:
      - zlib1g
      - liblzma5
      - liblzo2-2
      - libpng16-16
  
  scripts:
    plugin: dump
    source: src/scripts
    source-type: local
    organize:
      '*': usr/games/openttd/scripts/
  opengfx:
    plugin: dump
    source: https://cdn.openttd.org/opengfx-releases/0.6.1/opengfx-0.6.1-all.zip
    organize:
      opengfx-*.tar: usr/games/openttd/baseset/

  opensfx:
    plugin: dump
    source: https://cdn.openttd.org/opensfx-releases/1.0.1/opensfx-1.0.1-all.zip
    organize:
      opensfx-*: usr/games/openttd/baseset/

  openmsx:
    plugin: dump
    source: https://cdn.openttd.org/openmsx-releases/0.4.0/openmsx-0.4.0-all.zip
    organize:
      openmsx-*: usr/games/openttd/baseset/
